AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress(ErrorMessage="This is not a valid Email Address")]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using AarhusWebDevCoop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {

        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            MailMessage message = new MailMessage();
            message.To.Add("cqtkbnns@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("cqtkbnns@gmail.com", "yquqdmowgzpfkxpv");
                smtp.EnableSsl = true;
                // send mail
                try
                {
                    smtp.Send(message);
                    TempData["success"] = true;
                }
                catch (SmtpException ex)
                {
                    var Message = ex.Message.ToString();
                    // ex.FailedRecipient and ex.GetBaseException() should give you enough info.
                }

            }
            
            //saving the message

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "messages");

            comment.SetValue("vmname", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("message", model.Message);

            //save
            Services.ContentService.Save(comment);

            return RedirectToCurrentUmbracoPage();


        }



    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("gridLayout")

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("articleTitle")</h2>
<section>
	<p>@Umbraco.Field("articleContent")</p>
</section>

AarhusWebDevCoop/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("articlesTitle")</h2>
<section>
	<p>@Umbraco.Field("articlesBodyText")</p>
</section>
<section>
	@Umbraco.RenderMacro("ArticleList")
</section>

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h1>@CurrentPage.Name</h1>
	<div>
		@Html.Action("Index", "ContactFormSurface")
	</div>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<section id="main">
	@Umbraco.Field("contents")
</section>
<section id="articles">
     <h2>Latest Articles</h2>
	@Umbraco.RenderMacro("FiveNewestArticles")
</section>  
<section id="projects">
     <h2>Latest Projects</h2>
	@Umbraco.RenderMacro("FiveNewestCompletedProjects")
</section>  

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@if (!Members.GetCurrentLoginStatus().IsLoggedIn) { 
	@Umbraco.RenderMacro("LoginForm")
} else {
	@Umbraco.RenderMacro("Logout")
}

AarhusWebDevCoop/Views/MacroPartials/ArticleList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

<ul>
    @foreach (var item in selection)
    {
        <li><a href="@item.Url">@item.Name</a></li>
    }
</ul>

AarhusWebDevCoop/Views/MacroPartials/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm
@{
Layout = null;
}

@if (TempData["success"] == null)  {     
	// display the form 
	using(Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object{ }, new { @class = "form-horizontal"}))
	{
		<div class="form-group">
			@Html.LabelFor(m => m.Name, new{ @class = "col-sm-2 control-label"})
			<div class="col-sm-6">
				@Html.TextBoxFor(m => m.Name, new{ @class = "form-control", placeholder = "Name"})
				@Html.ValidationMessageFor(m => m.Name)
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Email, new{ @class = "col-sm-2 control-label"})
			<div class="col-sm-6">
				@Html.TextBoxFor(m => m.Email, new{ @class = "form-control", placeholder = "Email address"})
				@Html.ValidationMessageFor(m => m.Email)
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Subject, new{ @class = "col-sm-2 control-label"})
			<div class="col-sm-6">
				@Html.TextBoxFor(m => m.Subject, new{ @class = "form-control", placeholder = "Subject"})
				@Html.ValidationMessageFor(m => m.Subject)
			</div>
		</div>
		<div class="form-group">
			@Html.LabelFor(m => m.Message, new{ @class = "col-sm-2 control-label"})
			<div class="col-sm-6">
				@Html.TextAreaFor(m => m.Message, new{ @class = "form-control", placeholder = "Your message", rows="5"})
				@Html.ValidationMessageFor(m => m.Message)

			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-6">
				<button id="contact-submit" 
						type="submit" 
						class="btn btn-primary input-medium pull-left">
							Send
				</button>
			</div>
		</div>
	}
	
	} else {     
	<p>Thank you for contacting us. We’ll be in touch soon!</p> 
} 

AarhusWebDevCoop/Views/MacroPartials/FiveNewestArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

	<ul>
	@{
		var projects = CurrentPage.AncestorOrSelf(1).Children.Where("DocumentTypeAlias = \"articlesMain\"").First().Children.OrderBy("createDate desc");
		foreach(var page in projects){
				<li><a href="@page.Url">@page.Name</a></li>
			}
	}
	</ul>

AarhusWebDevCoop/Views/MacroPartials/FiveNewestCompetedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

	<ul>
	@{
		var projects = CurrentPage.AncestorOrSelf(1).Children.Where("DocumentTypeAlias = \"projectsMain\"").First().Children.OrderBy("createDate desc");
		
		foreach(var page in projects.Take(5)){
			
			var currentProjectStatus =  umbraco.library.GetPreValueAsString(page.projectStatus);
							
				if (currentProjectStatus == "Completed"){
					<li><a href="@page.Url">@page.Name</a></li>
				}
			}
	}
	</ul>

AarhusWebDevCoop/Views/MacroPartials/FiveNewestCompletedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

	<ul>
	@{
		var projects = CurrentPage.AncestorOrSelf(1).Children.Where("DocumentTypeAlias = \"projectsMain\"").First().Children.OrderBy("createDate desc");
		foreach(var page in projects){
			var currentProjectStatus =  umbraco.library.GetPreValueAsString(page.projectStatus);
							
				if (currentProjectStatus == "Completed"){
					<li><a href="@page.Url">@page.Name</a></li>
				}
			}
	}
	</ul>

AarhusWebDevCoop/Views/MacroPartials/LoginForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    <fieldset>
        <legend>Login</legend>
        
        @Html.ValidationSummary("loginModel", true)

        @Html.LabelFor(m => loginModel.Username)
        @Html.TextBoxFor(m => loginModel.Username)
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password)
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />

        <button>Login</button>
    </fieldset>  
}

AarhusWebDevCoop/Views/MacroPartials/Logout.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginStatusModel = Members.GetCurrentLoginStatus();

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");

    var logoutModel = new PostRedirectModel();
    
    @*
        Here you can specify a redirect URL for after logging out, by default umbraco will simply
        redirect to the current page. Example to redirect to the home page:
        
        logoutModel.RedirectUrl = "/"; 
    *@
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@if (loginStatusModel.IsLoggedIn)
{
    <p>You are currently logged in as @loginStatusModel.Name</p>

    using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
    {
         <fieldset>
             <legend>Logout</legend>
             <button>Logout</button>
         </fieldset>
    
        @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }
}

AarhusWebDevCoop/Views/MacroPartials/ProjectList.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

<ul>
    @foreach (var item in selection)
    {
        <li><a href="@item.Url">@item.Name</a></li>
    }
</ul>

AarhusWebDevCoop/Views/MacroPartials/SiteMap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
 
	<h4>Site Map</h4>
	
	@{var root = CurrentPage.AncestorOrSelf(1);} 

	<ul>		
		<li><a href="@root.Url">@root.Name</a></li>
		<li>
			@TraverseHelper(root.Id)
		</li>
	</ul>

@helper TraverseHelper(int rootId)
{
	var childrenPages = Umbraco.Content(rootId).Children;
	<ul>
    @foreach(var page in childrenPages){
		if(page.Name!="Site Map"){
		<li><a href="@page.Url">@page.Name</a></li>
			if(page.Children.Count() >0){
				<li>
					@TraverseHelper(page.Id)
				</li>
			}
		}
	}
	</ul>
	
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>@Umbraco.Field("siteTitle", recursive: true)</title>
	
	<meta name="description" content='@Umbraco.Field("metaDescription")'>
	<meta name="keywords" content='@Umbraco.Field("metaKeywords")'>
	<meta name="author" content="Liga Daine">

	<meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
	 <link href="css/style.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
	<script src="~/Scripts/jquery.validate.min.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>

	<div class="container">
		<header>
			<h1 id="title">@Umbraco.Field("siteTitle", recursive: true)</h1>
		</header>
		<nav class="navbar navbar-default">
			<div id="container-fluid">
			  <div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				</button>
			  </div>
			  <div id="navbar" class="navbar-collapse collapse">
				  @{var root = CurrentPage.AncestorOrSelf(1);}  
				<ul class="nav navbar-nav navbar-right">
					<li class="@((CurrentPage.Name == root.Name) ? "active" : null)">
						<a href="@root.Url">Home</a>
					</li>
@foreach (var menuItem in root.Children.Where("Visible")) { 
	var isProtected = umbraco.library.IsProtected(menuItem.id, menuItem.path); 
	var loginAccess = umbraco.library.IsProtected(menuItem.id, menuItem.path) && umbraco.library.HasAccess(menuItem.id, menuItem.path);
	if (!isProtected || loginAccess) { 
		<li class="@(menuItem.IsAncestorOrSelf(CurrentPage) ? "active" : null)"> 
			<a href="@menuItem.Url">@menuItem.Name</a> 
		</li>
	}
}
				  
					<!-- DROP DOWN MENU-->
					@{var umbracoDropdown = 
							root
							.Children
							.Where("DocumentTypeAlias=\"projectsMain\"")
							.First()
							.Children
							.Where("Visible")
							.OrderBy("Name");
					 }
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" 
						  data-toggle="dropdown" 
						  role="button" 
						  aria-haspopup="true" aria-expanded="false">
						  Our Projects 
						  <span class="caret"></span>
					</a>
					
					<ul class="dropdown-menu">
						@foreach (var menuItem in umbracoDropdown) { 
							//Displaying only projects, which are completed
							var test =  umbraco.library.GetPreValueAsString(menuItem.projectStatus);
							
							if (test == "Completed"){
								<li><a href="@menuItem.Url">@menuItem.Name</a></li>
							}
						}
					  </ul>
			      </li>
				</ul>
			  </div>
			</div>
		</nav>
						  
			@RenderBody()
	
		<footer class="wrapper">
			<h3>@Umbraco.Field("footer", recursive: true)</h3>
		</footer>
	</div>

</body>
</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@{
	var memberService = ApplicationContext.Current.Services.MemberService;
	var members = memberService.GetMembersByGroup("Active");
}

@foreach (var member in members) { 
	
	<p> @member.GetValue("firstname") 
		@member.GetValue("lastname") <br> 
		@member.GetValue("address")<br> 
		@member.GetValue("zip") 
		@member.GetValue("city")) <br> 
		Email: @member.Email<br> </p> 
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AarhusWebDevCoop/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

AarhusWebDevCoop/Views/ProjectItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("projectTitle")</h2>
	<section>
		<p>@Umbraco.Field("projectContent")</p>
	</section>

AarhusWebDevCoop/Views/ProjectsMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectsMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("projectsTitle")</h2>
<section>
	<p>@Umbraco.Field("projectsBodyText")</p>
	
</section>
<section>
	@Umbraco.RenderMacro("ProjectList")
</section>

AarhusWebDevCoop/Views/SiteMap.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.SiteMap>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@Umbraco.RenderMacro("SiteMap")

AarhusWebDevCoop/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h2>@Umbraco.Field("textPageHeader")</h2>
<section>
	<p>@Umbraco.Field("textPageMainContent")</p>
</section>